### ISSUE TITLE
Bug: Art-Saver dos not work on Furaffinity anymore

### ISSUE THREAD

**Issue by Tinsus** [solorey/Art-Saver#25]
neither the small icon when hovering an image appears or the button in the toolbar (using Firefox) works on furaffinity.net (only indicating a never ending loading process).

Error doesn't appear on other supported files.

**Comment by solorey** [comment]
This seems similar to a previous issue https://github.com/solorey/Art-Saver/issues/24. I am unable to replicate the bug on my end but the current fix is to uninstall then reinstall the extension.

**Comment by Tinsus** [comment]
reinstalling (and loosing the database) fixed the issue.

**Comment by solorey** [comment]
I apologize that your database was lost. It can be rebuilt using the guide described in the wiki for each site if you still have the appropriate data in the file name or somewhere else.
If you and another person have encountered this issue then maybe others have as well. I am going to leave this open for now so that others may see it if they are experiencing the same problem.
I'm still not sure what caused this issue if reinstalling the extension without me needing to update it fixes it.
